
# config to database with mongodb (url)
spring:
  application:
    name: room-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/room
#config banner with html
  main:
    allow-circular-references: true
    banner-mode: console
  banner:
    location: static/banar.txt

# for log level
logging:
  level:
    root: INFO
    com.room service: DEBUG
    org.springframework.web: ERROR
